"use client"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { createContext, useContext } from 'react'
import { DawContext } from '@/daw/DawContext'
import { GlobalDawContext } from './GlobalDawContext'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const dawCtx = useContext(GlobalDawContext);



  return (
    <html lang="en">
      <GlobalDawContext.Provider value={dawCtx} >
        <body className={inter.className}>{children}</body>
      </GlobalDawContext.Provider>
    </html>
  )
}
